/Users/jonah/Library/Python/3.11/lib/python/site-packages/pytest_asyncio/plugin.py:207: PytestDeprecationWarning: The configuration option "asyncio_default_fixture_loop_scope" is unset.
The event loop scope for asynchronous fixtures will default to the fixture caching scope. Future versions of pytest-asyncio will default the loop scope for asynchronous fixtures to function scope. Set the default fixture loop scope explicitly in order to avoid unexpected behavior in the future. Valid fixture loop scopes are: "function", "class", "module", "package", "session"

  warnings.warn(PytestDeprecationWarning(_DEFAULT_FIXTURE_LOOP_SCOPE_UNSET))
============================= test session starts ==============================
platform darwin -- Python 3.11.2, pytest-8.3.5, pluggy-1.5.0 -- /Library/Frameworks/Python.framework/Versions/3.11/bin/python3.11
cachedir: .pytest_cache
metadata: {'Python': '3.11.2', 'Platform': 'macOS-15.6-arm64-arm-64bit', 'Packages': {'pytest': '8.3.5', 'pluggy': '1.5.0'}, 'Plugins': {'timeout': '2.2.0', 'anyio': '4.11.0', 'html': '4.1.1', 'json-report': '1.5.0', 'metadata': '3.1.1', 'cov': '4.1.0', 'asyncio': '0.25.3', 'order': '1.3.0', 'mock': '3.14.0', 'xdist': '3.6.1', 'docker': '3.1.1'}}
rootdir: /Volumes/PRO-G40/Code/omnibase_core/tests
configfile: pytest.ini
plugins: timeout-2.2.0, anyio-4.11.0, html-4.1.1, json-report-1.5.0, metadata-3.1.1, cov-4.1.0, asyncio-0.25.3, order-1.3.0, mock-3.14.0, xdist-3.6.1, docker-3.1.1
asyncio: mode=Mode.STRICT, asyncio_default_fixture_loop_scope=None
collecting ... collected 279 items / 141 errors / 1 skipped

==================================== ERRORS ====================================
________ ERROR collecting performance/test_model_timeout_performance.py ________
ImportError while importing test module '/Volumes/PRO-G40/Code/omnibase_core/tests/performance/test_model_timeout_performance.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/performance/test_model_timeout_performance.py:14: in <module>
    from omnibase_core.enums.enum_runtime_category import EnumRuntimeCategory
E   ModuleNotFoundError: No module named 'omnibase_core'
______ ERROR collecting unit/container/test_container_service_resolver.py ______
ImportError while importing test module '/Volumes/PRO-G40/Code/omnibase_core/tests/unit/container/test_container_service_resolver.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/unit/container/test_container_service_resolver.py:17: in <module>
    from omnibase_core.container.container_service_resolver import (
E   ModuleNotFoundError: No module named 'omnibase_core'
_______ ERROR collecting unit/contracts/test_model_compensation_plan.py ________
ImportError while importing test module '/Volumes/PRO-G40/Code/omnibase_core/tests/unit/contracts/test_model_compensation_plan.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/unit/contracts/test_model_compensation_plan.py:21: in <module>
    from omnibase_core.enums.enum_compensation_strategy import EnumCompensationStrategy
E   ModuleNotFoundError: No module named 'omnibase_core'
_________ ERROR collecting unit/contracts/test_model_contract_base.py __________
ImportError while importing test module '/Volumes/PRO-G40/Code/omnibase_core/tests/unit/contracts/test_model_contract_base.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/unit/contracts/test_model_contract_base.py:20: in <module>
    from omnibase_core.enums import EnumNodeType
E   ModuleNotFoundError: No module named 'omnibase_core'
______ ERROR collecting unit/contracts/test_model_effect_retry_config.py _______
ImportError while importing test module '/Volumes/PRO-G40/Code/omnibase_core/tests/unit/contracts/test_model_effect_retry_config.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/unit/contracts/test_model_effect_retry_config.py:11: in <module>
    from omnibase_core.enums.enum_retry_backoff_strategy import EnumRetryBackoffStrategy
E   ModuleNotFoundError: No module named 'omnibase_core'
____ ERROR collecting unit/contracts/test_model_external_service_config.py _____
ImportError while importing test module '/Volumes/PRO-G40/Code/omnibase_core/tests/unit/contracts/test_model_external_service_config.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/unit/contracts/test_model_external_service_config.py:11: in <module>
    from omnibase_core.enums.enum_auth_type import EnumAuthType
E   ModuleNotFoundError: No module named 'omnibase_core'
________ ERROR collecting unit/contracts/test_model_trigger_mappings.py ________
ImportError while importing test module '/Volumes/PRO-G40/Code/omnibase_core/tests/unit/contracts/test_model_trigger_mappings.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/unit/contracts/test_model_trigger_mappings.py:21: in <module>
    from omnibase_core.enums.enum_core_error_code import EnumCoreErrorCode
E   ModuleNotFoundError: No module named 'omnibase_core'
________________ ERROR collecting unit/core/test_decorators.py _________________
ImportError while importing test module '/Volumes/PRO-G40/Code/omnibase_core/tests/unit/core/test_decorators.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/unit/core/test_decorators.py:10: in <module>
    from omnibase_core.utils.decorators import allow_any_type, allow_dict_str_any
E   ModuleNotFoundError: No module named 'omnibase_core'
___________ ERROR collecting unit/core/test_model_base_collection.py ___________
ImportError while importing test module '/Volumes/PRO-G40/Code/omnibase_core/tests/unit/core/test_model_base_collection.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/unit/core/test_model_base_collection.py:13: in <module>
    from omnibase_core.models.base.model_collection import ModelBaseCollection
E   ModuleNotFoundError: No module named 'omnibase_core'
____________ ERROR collecting unit/core/test_model_base_factory.py _____________
ImportError while importing test module '/Volumes/PRO-G40/Code/omnibase_core/tests/unit/core/test_model_base_factory.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/unit/core/test_model_base_factory.py:11: in <module>
    from omnibase_core.models.base.model_factory import ModelBaseFactory
E   ModuleNotFoundError: No module named 'omnibase_core'
___________ ERROR collecting unit/core/test_model_base_processor.py ____________
ImportError while importing test module '/Volumes/PRO-G40/Code/omnibase_core/tests/unit/core/test_model_base_processor.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/unit/core/test_model_base_processor.py:11: in <module>
    from omnibase_core.models.base.model_processor import ModelServiceBaseProcessor
E   ModuleNotFoundError: No module named 'omnibase_core'
___________ ERROR collecting unit/core/test_model_generic_factory.py ___________
ImportError while importing test module '/Volumes/PRO-G40/Code/omnibase_core/tests/unit/core/test_model_generic_factory.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/unit/core/test_model_generic_factory.py:8: in <module>
    from omnibase_core.enums.enum_validation_severity import EnumValidationSeverity
E   ModuleNotFoundError: No module named 'omnibase_core'
_________ ERROR collecting unit/core/test_protocol_implementations.py __________
ImportError while importing test module '/Volumes/PRO-G40/Code/omnibase_core/tests/unit/core/test_protocol_implementations.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/unit/core/test_protocol_implementations.py:11: in <module>
    from omnibase_core.types.constraints import (
E   ModuleNotFoundError: No module named 'omnibase_core'
_____________ ERROR collecting unit/core/test_type_constraints.py ______________
ImportError while importing test module '/Volumes/PRO-G40/Code/omnibase_core/tests/unit/core/test_type_constraints.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/unit/core/test_type_constraints.py:11: in <module>
    from omnibase_core.types.constraints import (
E   ModuleNotFoundError: No module named 'omnibase_core'
___________ ERROR collecting unit/enums/test_enum_action_category.py ___________
ImportError while importing test module '/Volumes/PRO-G40/Code/omnibase_core/tests/unit/enums/test_enum_action_category.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/unit/enums/test_enum_action_category.py:13: in <module>
    from omnibase_core.enums.enum_action_category import EnumActionCategory
E   ModuleNotFoundError: No module named 'omnibase_core'
____________ ERROR collecting unit/enums/test_enum_artifact_type.py ____________
ImportError while importing test module '/Volumes/PRO-G40/Code/omnibase_core/tests/unit/enums/test_enum_artifact_type.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/unit/enums/test_enum_artifact_type.py:16: in <module>
    from omnibase_core.enums.enum_artifact_type import EnumArtifactType
E   ModuleNotFoundError: No module named 'omnibase_core'
______________ ERROR collecting unit/enums/test_enum_auth_type.py ______________
ImportError while importing test module '/Volumes/PRO-G40/Code/omnibase_core/tests/unit/enums/test_enum_auth_type.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/unit/enums/test_enum_auth_type.py:18: in <module>
    from omnibase_core.enums.enum_auth_type import EnumAuthType
E   ModuleNotFoundError: No module named 'omnibase_core'
___________ ERROR collecting unit/enums/test_enum_category_filter.py ___________
ImportError while importing test module '/Volumes/PRO-G40/Code/omnibase_core/tests/unit/enums/test_enum_category_filter.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/unit/enums/test_enum_category_filter.py:7: in <module>
    from omnibase_core.enums import EnumCategoryFilter
E   ModuleNotFoundError: No module named 'omnibase_core'
______________ ERROR collecting unit/enums/test_enum_cell_type.py ______________
ImportError while importing test module '/Volumes/PRO-G40/Code/omnibase_core/tests/unit/enums/test_enum_cell_type.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/unit/enums/test_enum_cell_type.py:17: in <module>
    from omnibase_core.enums.enum_cell_type import EnumCellType
E   ModuleNotFoundError: No module named 'omnibase_core'
_____________ ERROR collecting unit/enums/test_enum_cli_status.py ______________
ImportError while importing test module '/Volumes/PRO-G40/Code/omnibase_core/tests/unit/enums/test_enum_cli_status.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/unit/enums/test_enum_cli_status.py:16: in <module>
    from omnibase_core.enums.enum_cli_status import EnumCliStatus
E   ModuleNotFoundError: No module named 'omnibase_core'
__________ ERROR collecting unit/enums/test_enum_collection_format.py __________
ImportError while importing test module '/Volumes/PRO-G40/Code/omnibase_core/tests/unit/enums/test_enum_collection_format.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/unit/enums/test_enum_collection_format.py:19: in <module>
    from omnibase_core.enums.enum_collection_format import EnumCollectionFormat
E   ModuleNotFoundError: No module named 'omnibase_core'
________ ERROR collecting unit/enums/test_enum_compensation_strategy.py ________
ImportError while importing test module '/Volumes/PRO-G40/Code/omnibase_core/tests/unit/enums/test_enum_compensation_strategy.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/unit/enums/test_enum_compensation_strategy.py:18: in <module>
    from omnibase_core.enums.enum_compensation_strategy import EnumCompensationStrategy
E   ModuleNotFoundError: No module named 'omnibase_core'
___________ ERROR collecting unit/enums/test_enum_config_category.py ___________
ImportError while importing test module '/Volumes/PRO-G40/Code/omnibase_core/tests/unit/enums/test_enum_config_category.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/unit/enums/test_enum_config_category.py:18: in <module>
    from omnibase_core.enums.enum_config_category import EnumConfigCategory
E   ModuleNotFoundError: No module named 'omnibase_core'
_________ ERROR collecting unit/enums/test_enum_data_classification.py _________
ImportError while importing test module '/Volumes/PRO-G40/Code/omnibase_core/tests/unit/enums/test_enum_data_classification.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/unit/enums/test_enum_data_classification.py:18: in <module>
    from omnibase_core.enums.enum_data_classification import EnumDataClassification
E   ModuleNotFoundError: No module named 'omnibase_core'
______________ ERROR collecting unit/enums/test_enum_data_type.py ______________
ImportError while importing test module '/Volumes/PRO-G40/Code/omnibase_core/tests/unit/enums/test_enum_data_type.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/unit/enums/test_enum_data_type.py:18: in <module>
    from omnibase_core.enums.enum_data_type import EnumDataType
E   ModuleNotFoundError: No module named 'omnibase_core'
_____________ ERROR collecting unit/enums/test_enum_debug_level.py _____________
ImportError while importing test module '/Volumes/PRO-G40/Code/omnibase_core/tests/unit/enums/test_enum_debug_level.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/unit/enums/test_enum_debug_level.py:19: in <module>
    from omnibase_core.enums.enum_debug_level import EnumDebugLevel
E   ModuleNotFoundError: No module named 'omnibase_core'
________ ERROR collecting unit/enums/test_enum_documentation_quality.py ________
ImportError while importing test module '/Volumes/PRO-G40/Code/omnibase_core/tests/unit/enums/test_enum_documentation_quality.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/unit/enums/test_enum_documentation_quality.py:12: in <module>
    from omnibase_core.enums.enum_documentation_quality import EnumDocumentationQuality
E   ModuleNotFoundError: No module named 'omnibase_core'
_____________ ERROR collecting unit/enums/test_enum_environment.py _____________
ImportError while importing test module '/Volumes/PRO-G40/Code/omnibase_core/tests/unit/enums/test_enum_environment.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/unit/enums/test_enum_environment.py:19: in <module>
    from omnibase_core.enums.enum_environment import EnumEnvironment
E   ModuleNotFoundError: No module named 'omnibase_core'
__________ ERROR collecting unit/enums/test_enum_execution_status.py ___________
ImportError while importing test module '/Volumes/PRO-G40/Code/omnibase_core/tests/unit/enums/test_enum_execution_status.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/unit/enums/test_enum_execution_status.py:18: in <module>
    from omnibase_core.enums.enum_execution_status import EnumExecutionStatus
E   ModuleNotFoundError: No module named 'omnibase_core'
_____________ ERROR collecting unit/enums/test_enum_filter_type.py _____________
ImportError while importing test module '/Volumes/PRO-G40/Code/omnibase_core/tests/unit/enums/test_enum_filter_type.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/unit/enums/test_enum_filter_type.py:16: in <module>
    from omnibase_core.enums.enum_filter_type import EnumFilterType
E   ModuleNotFoundError: No module named 'omnibase_core'
____________ ERROR collecting unit/enums/test_enum_instance_type.py ____________
ImportError while importing test module '/Volumes/PRO-G40/Code/omnibase_core/tests/unit/enums/test_enum_instance_type.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/unit/enums/test_enum_instance_type.py:9: in <module>
    from omnibase_core.enums.enum_instance_type import EnumInstanceType
E   ModuleNotFoundError: No module named 'omnibase_core'
______________ ERROR collecting unit/enums/test_enum_item_type.py ______________
ImportError while importing test module '/Volumes/PRO-G40/Code/omnibase_core/tests/unit/enums/test_enum_item_type.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/unit/enums/test_enum_item_type.py:11: in <module>
    from omnibase_core.enums.enum_item_type import EnumItemType
E   ModuleNotFoundError: No module named 'omnibase_core'
_________ ERROR collecting unit/enums/test_enum_metadata_node_type.py __________
ImportError while importing test module '/Volumes/PRO-G40/Code/omnibase_core/tests/unit/enums/test_enum_metadata_node_type.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/unit/enums/test_enum_metadata_node_type.py:17: in <module>
    from omnibase_core.enums.enum_metadata_node_type import EnumMetadataNodeType
E   ModuleNotFoundError: No module named 'omnibase_core'
__________ ERROR collecting unit/enums/test_enum_metric_data_type.py ___________
ImportError while importing test module '/Volumes/PRO-G40/Code/omnibase_core/tests/unit/enums/test_enum_metric_data_type.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/unit/enums/test_enum_metric_data_type.py:7: in <module>
    from omnibase_core.enums.enum_metric_data_type import EnumMetricDataType
E   ModuleNotFoundError: No module named 'omnibase_core'
__________ ERROR collecting unit/enums/test_enum_metrics_category.py ___________
ImportError while importing test module '/Volumes/PRO-G40/Code/omnibase_core/tests/unit/enums/test_enum_metrics_category.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/unit/enums/test_enum_metrics_category.py:7: in <module>
    from omnibase_core.enums.enum_metrics_category import EnumMetricsCategory
E   ModuleNotFoundError: No module named 'omnibase_core'
______________ ERROR collecting unit/enums/test_enum_node_type.py ______________
ImportError while importing test module '/Volumes/PRO-G40/Code/omnibase_core/tests/unit/enums/test_enum_node_type.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/unit/enums/test_enum_node_type.py:7: in <module>
    from omnibase_core.enums import EnumNodeType
E   ModuleNotFoundError: No module named 'omnibase_core'
____________ ERROR collecting unit/enums/test_enum_numeric_type.py _____________
ImportError while importing test module '/Volumes/PRO-G40/Code/omnibase_core/tests/unit/enums/test_enum_numeric_type.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/unit/enums/test_enum_numeric_type.py:17: in <module>
    from omnibase_core.enums.enum_numeric_type import EnumNumericType
E   ModuleNotFoundError: No module named 'omnibase_core'
___________ ERROR collecting unit/enums/test_enum_parameter_type.py ____________
ImportError while importing test module '/Volumes/PRO-G40/Code/omnibase_core/tests/unit/enums/test_enum_parameter_type.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/unit/enums/test_enum_parameter_type.py:7: in <module>
    from omnibase_core.enums import EnumParameterType
E   ModuleNotFoundError: No module named 'omnibase_core'
___________ ERROR collecting unit/enums/test_enum_registry_status.py ___________
ImportError while importing test module '/Volumes/PRO-G40/Code/omnibase_core/tests/unit/enums/test_enum_registry_status.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/unit/enums/test_enum_registry_status.py:16: in <module>
    from omnibase_core.enums.enum_registry_status import EnumRegistryStatus
E   ModuleNotFoundError: No module named 'omnibase_core'
_______ ERROR collecting unit/enums/test_enum_retry_backoff_strategy.py ________
ImportError while importing test module '/Volumes/PRO-G40/Code/omnibase_core/tests/unit/enums/test_enum_retry_backoff_strategy.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/unit/enums/test_enum_retry_backoff_strategy.py:16: in <module>
    from omnibase_core.enums.enum_retry_backoff_strategy import EnumRetryBackoffStrategy
E   ModuleNotFoundError: No module named 'omnibase_core'
_____________ ERROR collecting unit/enums/test_enum_return_type.py _____________
ImportError while importing test module '/Volumes/PRO-G40/Code/omnibase_core/tests/unit/enums/test_enum_return_type.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/unit/enums/test_enum_return_type.py:7: in <module>
    from omnibase_core.enums import EnumReturnType
E   ModuleNotFoundError: No module named 'omnibase_core'
___________ ERROR collecting unit/enums/test_enum_scenario_status.py ___________
ImportError while importing test module '/Volumes/PRO-G40/Code/omnibase_core/tests/unit/enums/test_enum_scenario_status.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/unit/enums/test_enum_scenario_status.py:16: in <module>
    from omnibase_core.enums.enum_scenario_status import EnumScenarioStatus
E   ModuleNotFoundError: No module named 'omnibase_core'
___________ ERROR collecting unit/enums/test_enum_severity_level.py ____________
ImportError while importing test module '/Volumes/PRO-G40/Code/omnibase_core/tests/unit/enums/test_enum_severity_level.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/unit/enums/test_enum_severity_level.py:20: in <module>
    from omnibase_core.enums.enum_severity_level import EnumSeverityLevel
E   ModuleNotFoundError: No module named 'omnibase_core'
_______________ ERROR collecting unit/enums/test_enum_status.py ________________
ImportError while importing test module '/Volumes/PRO-G40/Code/omnibase_core/tests/unit/enums/test_enum_status.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/unit/enums/test_enum_status.py:18: in <module>
    from omnibase_core.enums.enum_status import EnumStatus
E   ModuleNotFoundError: No module named 'omnibase_core'
___________ ERROR collecting unit/enums/test_enum_status_message.py ____________
ImportError while importing test module '/Volumes/PRO-G40/Code/omnibase_core/tests/unit/enums/test_enum_status_message.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/unit/enums/test_enum_status_message.py:7: in <module>
    from omnibase_core.enums.enum_status_message import EnumStatusMessage
E   ModuleNotFoundError: No module named 'omnibase_core'
______________ ERROR collecting unit/enums/test_enum_type_name.py ______________
ImportError while importing test module '/Volumes/PRO-G40/Code/omnibase_core/tests/unit/enums/test_enum_type_name.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/unit/enums/test_enum_type_name.py:18: in <module>
    from omnibase_core.enums.enum_type_name import EnumTypeName
E   ModuleNotFoundError: No module named 'omnibase_core'
_________ ERROR collecting unit/enums/test_enum_validation_severity.py _________
ImportError while importing test module '/Volumes/PRO-G40/Code/omnibase_core/tests/unit/enums/test_enum_validation_severity.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/unit/enums/test_enum_validation_severity.py:18: in <module>
    from omnibase_core.enums.enum_validation_severity import EnumValidationSeverity
E   ModuleNotFoundError: No module named 'omnibase_core'
_________ ERROR collecting unit/enums/test_unified_status_hierarchy.py _________
ImportError while importing test module '/Volumes/PRO-G40/Code/omnibase_core/tests/unit/enums/test_unified_status_hierarchy.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/unit/enums/test_unified_status_hierarchy.py:10: in <module>
    from omnibase_core.enums.enum_base_status import EnumBaseStatus
E   ModuleNotFoundError: No module named 'omnibase_core'
_______________ ERROR collecting unit/errors/test_error_codes.py _______________
ImportError while importing test module '/Volumes/PRO-G40/Code/omnibase_core/tests/unit/errors/test_error_codes.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/unit/errors/test_error_codes.py:21: in <module>
    from omnibase_core.enums.enum_onex_status import EnumOnexStatus
E   ModuleNotFoundError: No module named 'omnibase_core'
_____________ ERROR collecting unit/exceptions/test_onex_error.py ______________
ImportError while importing test module '/Volumes/PRO-G40/Code/omnibase_core/tests/unit/exceptions/test_onex_error.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/unit/exceptions/test_onex_error.py:15: in <module>
    from omnibase_core.enums.enum_core_error_code import EnumCoreErrorCode
E   ModuleNotFoundError: No module named 'omnibase_core'
__________________ ERROR collecting unit/logging/test_emit.py __________________
ImportError while importing test module '/Volumes/PRO-G40/Code/omnibase_core/tests/unit/logging/test_emit.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/unit/logging/test_emit.py:20: in <module>
    from omnibase_core.enums.enum_log_level import EnumLogLevel as LogLevel
E   ModuleNotFoundError: No module named 'omnibase_core'
______ ERROR collecting unit/models/cli/test_model_cli_advanced_params.py ______
ImportError while importing test module '/Volumes/PRO-G40/Code/omnibase_core/tests/unit/models/cli/test_model_cli_advanced_params.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/unit/models/cli/test_model_cli_advanced_params.py:10: in <module>
    from omnibase_core.enums.enum_debug_level import EnumDebugLevel
E   ModuleNotFoundError: No module named 'omnibase_core'
________ ERROR collecting unit/models/cli/test_model_cli_debug_info.py _________
ImportError while importing test module '/Volumes/PRO-G40/Code/omnibase_core/tests/unit/models/cli/test_model_cli_debug_info.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/unit/models/cli/test_model_cli_debug_info.py:9: in <module>
    from omnibase_core.models.cli.model_cli_debug_info import ModelCliDebugInfo
E   ModuleNotFoundError: No module named 'omnibase_core'
_____ ERROR collecting unit/models/cli/test_model_cli_execution_config.py ______
ImportError while importing test module '/Volumes/PRO-G40/Code/omnibase_core/tests/unit/models/cli/test_model_cli_execution_config.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/unit/models/cli/test_model_cli_execution_config.py:12: in <module>
    from omnibase_core.enums.enum_output_format import EnumOutputFormat
E   ModuleNotFoundError: No module named 'omnibase_core'
_____ ERROR collecting unit/models/cli/test_model_cli_execution_context.py _____
ImportError while importing test module '/Volumes/PRO-G40/Code/omnibase_core/tests/unit/models/cli/test_model_cli_execution_context.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/unit/models/cli/test_model_cli_execution_context.py:14: in <module>
    from omnibase_core.enums.enum_context_source import EnumContextSource
E   ModuleNotFoundError: No module named 'omnibase_core'
______ ERROR collecting unit/models/cli/test_model_cli_execution_core.py _______
ImportError while importing test module '/Volumes/PRO-G40/Code/omnibase_core/tests/unit/models/cli/test_model_cli_execution_core.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/unit/models/cli/test_model_cli_execution_core.py:14: in <module>
    from omnibase_core.enums.enum_execution_phase import EnumExecutionPhase
E   ModuleNotFoundError: No module named 'omnibase_core'
______ ERROR collecting unit/models/cli/test_model_cli_execution_fixes.py ______
ImportError while importing test module '/Volumes/PRO-G40/Code/omnibase_core/tests/unit/models/cli/test_model_cli_execution_fixes.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/unit/models/cli/test_model_cli_execution_fixes.py:11: in <module>
    from omnibase_core.enums.enum_context_source import EnumContextSource
E   ModuleNotFoundError: No module named 'omnibase_core'
____ ERROR collecting unit/models/cli/test_model_cli_execution_metadata.py _____
ImportError while importing test module '/Volumes/PRO-G40/Code/omnibase_core/tests/unit/models/cli/test_model_cli_execution_metadata.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/unit/models/cli/test_model_cli_execution_metadata.py:10: in <module>
    from omnibase_core.enums.enum_context_source import EnumContextSource
E   ModuleNotFoundError: No module named 'omnibase_core'
______ ERROR collecting unit/models/cli/test_model_cli_result_metadata.py ______
ImportError while importing test module '/Volumes/PRO-G40/Code/omnibase_core/tests/unit/models/cli/test_model_cli_result_metadata.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/unit/models/cli/test_model_cli_result_metadata.py:12: in <module>
    from omnibase_core.enums.enum_data_classification import EnumDataClassification
E   ModuleNotFoundError: No module named 'omnibase_core'
_______ ERROR collecting unit/models/common/test_model_error_context.py ________
ImportError while importing test module '/Volumes/PRO-G40/Code/omnibase_core/tests/unit/models/common/test_model_error_context.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/unit/models/common/test_model_error_context.py:5: in <module>
    from omnibase_core.models.common.model_error_context import ModelErrorContext
E   ModuleNotFoundError: No module named 'omnibase_core'
_______ ERROR collecting unit/models/common/test_model_flexible_value.py _______
ImportError while importing test module '/Volumes/PRO-G40/Code/omnibase_core/tests/unit/models/common/test_model_flexible_value.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/Library/Frameworks/Pyt
